export const TYPE_NAVBAR = 'navbar'
export const TYPE_NAVBAR_MENU = 'navbar-menu'
export const TYPE_NAVBAR_LINK = 'navbar-link'
export const TYPE_NAV_GROUP = 'nav-group'
export const TYPE_DROPDOWN = 'nav-dropdown'
export const TYPE_DROPDOWN_ITEM = 'nav-dropdown-item'
export const TYPE_MEGA = 'nav-mega'
export const TYPE_MEGA_INNER = 'nav-mega-inner'
export const TYPE_MEGA_COL = 'nav-mega-col'
export const TYPE_MEGA_LEFT = 'nav-mega-left'
export const TYPE_MEGA_RIGHT = 'nav-mega-right'
export const TYPE_NAVBAR_LEFT = 'navbar-left-slot'
export const TYPE_NAVBAR_CENTER = 'navbar-center-slot'
export const TYPE_NAVBAR_RIGHT = 'navbar-right-slot'

export const NAVBAR_ICON = 'lucide:navigation-2'
